// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Cognito$ReasonCognito = require("./Cognito.bs.js");

var config = {
  UserPoolId: "us-east-2_pTFKTGtS3",
  ClientId: "3vjshpa4lgf92nfisjrg9os21a"
};

var userPool = Cognito$ReasonCognito.makeCognitoClient(config);

var signupMonad = Cognito$ReasonCognito.signUp(userPool, "patrick", "Password123", undefined, undefined, /* () */0);

exports.config = config;
exports.userPool = userPool;
exports.signupMonad = signupMonad;
/* userPool Not a pure module */
