// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    129319447,
    "ReactCognitoUnknownException"
  ],
  /* tuple */[
    359869661,
    "InvalidPasswordException"
  ]
];

function cognitoErrorCodesToJs(param) {
  return Js_mapperRt.binarySearch(2, param, jsMapperConstantArray);
}

function cognitoErrorCodesFromJs(param) {
  return Js_mapperRt.revSearch(2, jsMapperConstantArray, param);
}

exports.cognitoErrorCodesToJs = cognitoErrorCodesToJs;
exports.cognitoErrorCodesFromJs = cognitoErrorCodesFromJs;
/* No side effect */
